# Generated by Django 3.0.8 on 2020-07-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=5000)),
                ('head0', models.CharField(default='', max_length=5000)),
                ('head1', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(default='', max_length=5000)),
                ('pub_date', models.CharField(default='', max_length=5000)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
